apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: go-app
  template:
    metadata:
      labels:
        app: go-app 
    spec:
      containers:
        - name: go-app
          image: <ECR_URI>/eks-ecs
          ports:
            - containerPort: 8080
          env:
          - name: RDS_HOST
            value: "localhost"
          - name: RDS_PORT
            value: "3306"
          - name: RDS_USER
            value: "admin"
          - name: RDS_PASSWORD
            value: "password"
          - name: RDS_DB_NAME
            value: "db"
          - name: REDIS_HOST
            value: "localhost"
          - name: REDIS_PORT
            value: "6379"